# Generated by Django 3.1.3 on 2021-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210626_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private_account',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
