# Generated by Django 3.1.3 on 2021-07-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210714_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private_account',
            field=models.BooleanField(),
        ),
    ]
