# Generated by Django 3.1.3 on 2021-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210714_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png', null=True, upload_to='profile_pictures'),
        ),
    ]
