# Generated by Django 3.1.3 on 2021-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210716_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='/profile_pictures/defaultprofile.png', null=True, upload_to='profile_pictures'),
        ),
    ]
